const SB='https://pbanjavtyzcqllpcgizh.supabase.co';
const KEY='sb_publishable_Js7SEX1AZtmZbNzRLStxEw_S4zRTJ2V';
const KSESSION='kt_pwa_session';
const KSTATE='kt_pwa_state';

const I18N={
en:{tagline:'5-language realtime meeting translator',loginTitle:'Sign in',loginDesc:'Choose your language, enter your ID and name, then start.',idLabel:'User ID / Employee No.',nameLabel:'Name',start:'Start',loginNote:'Your selected language is used for both the whole screen and incoming translations.',connected:'Connected',createTitle:'Create meeting room',createDesc:'Create a room as host. Participants must be approved before chatting.',roomName:'Room name',create:'Create Room',joinTitle:'Join meeting room',joinDesc:'Enter the 6-character room code and wait for host approval.',code:'Room code',join:'Request to Join',roomInfo:'Meeting room',room:'Room',role:'Role',language:'Language',count:'Participants',participants:'Participants',refresh:'Refresh',security:'Only approved room members can read, send, or translate messages.',chat:'Meeting Chat',waitingTitle:'Waiting for host approval',waitingDesc:'This screen will update automatically after the host approves you.',blockedTitle:'Access denied',blockedDesc:'The host rejected or removed this participant.',send:'Send',logout:'Logout',host:'Host',member:'Member',approve:'Approve',reject:'Reject',remove:'Remove',pending:'Pending',approved:'Approved',noPending:'No pending participants.',type:'Type a message…',working:'Connecting…',creating:'Creating room…',joining:'Sending join request…',translate:'Translating…',invalidId:'Use 2–40 letters, numbers, dot, underscore, or hyphen for User ID.',needName:'Please enter your name.',duplicate:'This User ID is already in use.',loginFail:'Login failed.',needRoom:'Please enter a room name.',createFail:'Room creation failed.',badCode:'Enter a valid 6-character room code.',joinFail:'Join request failed.',roomFull:'The room is full.',notFound:'Room not found or closed.',decisionFail:'Could not update participant.',original:'Original',minutesTitle:'Meeting minutes',minutesNote:'Create minutes from the current chat.',minutesCreate:'Create minutes',minutesWorking:'Creating minutes…',minutesClose:'Close',saveTxt:'Save TXT',savePdf:'Save PDF',summary:'Summary',decisions:'Decisions',actions:'Action items',unresolved:'Unresolved items',none:'None',minutesFail:'Could not create meeting minutes.'},
ko:{tagline:'5개국어 실시간 회의 번역',loginTitle:'로그인',loginDesc:'언어를 선택하고 사용자 ID와 이름을 입력한 뒤 시작하세요.',idLabel:'사용자 ID / 사번',nameLabel:'이름',start:'시작',loginNote:'선택한 언어가 전체 화면과 수신 메시지 번역 언어에 함께 적용됩니다.',connected:'연결됨',createTitle:'회의방 만들기',createDesc:'방장으로 회의방을 만듭니다. 참가자는 승인 후 채팅할 수 있습니다.',roomName:'회의방 이름',create:'회의방 생성',joinTitle:'회의방 참가',joinDesc:'6자리 방 코드를 입력하고 방장 승인을 기다립니다.',code:'방 코드',join:'참가 요청',roomInfo:'회의방',room:'회의방',role:'역할',language:'언어',count:'참가자',participants:'참가자 관리',refresh:'새로고침',security:'승인된 방 참가자만 메시지를 읽고 보내고 번역할 수 있습니다.',chat:'회의 채팅',waitingTitle:'방장 승인 대기 중',waitingDesc:'방장이 승인하면 이 화면이 자동으로 바뀝니다.',blockedTitle:'입장 불가',blockedDesc:'방장이 참가 요청을 거절했거나 퇴장 처리했습니다.',send:'전송',logout:'로그아웃',host:'방장',member:'참가자',approve:'승인',reject:'거절',remove:'퇴장',pending:'승인 대기',approved:'승인됨',noPending:'승인 대기 참가자가 없습니다.',type:'메시지 입력…',working:'연결 중…',creating:'회의방 생성 중…',joining:'참가 요청 전송 중…',translate:'번역 중…',invalidId:'사용자 ID는 영문·숫자·점·밑줄·하이픈으로 2~40자 입력하세요.',needName:'이름을 입력하세요.',duplicate:'이미 사용 중인 사용자 ID입니다.',loginFail:'로그인에 실패했습니다.',needRoom:'회의방 이름을 입력하세요.',createFail:'회의방 생성에 실패했습니다.',badCode:'올바른 6자리 방 코드를 입력하세요.',joinFail:'참가 요청에 실패했습니다.',roomFull:'회의방 정원이 가득 찼습니다.',notFound:'회의방을 찾을 수 없거나 종료되었습니다.',decisionFail:'참가자 상태 변경에 실패했습니다.',original:'원문',minutesTitle:'회의록',minutesNote:'현재 채팅 내용으로 회의록을 작성합니다.',minutesCreate:'회의록 작성',minutesWorking:'회의록 작성 중…',minutesClose:'닫기',saveTxt:'메모장 저장',savePdf:'PDF 저장',summary:'회의 요약',decisions:'결정사항',actions:'실행항목',unresolved:'미해결 항목',none:'없음',minutesFail:'회의록 작성에 실패했습니다.'},
vi:{tagline:'Dịch cuộc họp thời gian thực 5 ngôn ngữ',loginTitle:'Đăng nhập',loginDesc:'Chọn ngôn ngữ, nhập ID và tên, sau đó bắt đầu.',idLabel:'ID người dùng / Mã nhân viên',nameLabel:'Tên',start:'Bắt đầu',loginNote:'Ngôn ngữ đã chọn áp dụng cho toàn bộ giao diện và bản dịch tin nhắn nhận.',connected:'Đã kết nối',createTitle:'Tạo phòng họp',createDesc:'Tạo phòng với vai trò chủ phòng. Người tham gia cần được duyệt.',roomName:'Tên phòng',create:'Tạo phòng',joinTitle:'Tham gia phòng họp',joinDesc:'Nhập mã phòng 6 ký tự và chờ chủ phòng duyệt.',code:'Mã phòng',join:'Gửi yêu cầu tham gia',roomInfo:'Phòng họp',room:'Phòng',role:'Vai trò',language:'Ngôn ngữ',count:'Người tham gia',participants:'Quản lý người tham gia',refresh:'Làm mới',security:'Chỉ thành viên đã được duyệt mới có thể đọc, gửi và dịch tin nhắn.',chat:'Chat cuộc họp',waitingTitle:'Đang chờ chủ phòng duyệt',waitingDesc:'Màn hình sẽ tự cập nhật sau khi được duyệt.',blockedTitle:'Không thể vào',blockedDesc:'Chủ phòng đã từ chối hoặc xóa người tham gia này.',send:'Gửi',logout:'Đăng xuất',host:'Chủ phòng',member:'Thành viên',approve:'Duyệt',reject:'Từ chối',remove:'Xóa',pending:'Đang chờ',approved:'Đã duyệt',noPending:'Không có người chờ duyệt.',type:'Nhập tin nhắn…',working:'Đang kết nối…',creating:'Đang tạo phòng…',joining:'Đang gửi yêu cầu…',translate:'Đang dịch…',invalidId:'ID gồm 2–40 ký tự chữ, số, dấu chấm, gạch dưới hoặc gạch nối.',needName:'Vui lòng nhập tên.',duplicate:'ID này đã được sử dụng.',loginFail:'Đăng nhập thất bại.',needRoom:'Vui lòng nhập tên phòng.',createFail:'Tạo phòng thất bại.',badCode:'Nhập mã phòng 6 ký tự hợp lệ.',joinFail:'Yêu cầu tham gia thất bại.',roomFull:'Phòng đã đầy.',notFound:'Không tìm thấy phòng hoặc phòng đã đóng.',decisionFail:'Không thể cập nhật người tham gia.',original:'Bản gốc',minutesTitle:'Biên bản cuộc họp',minutesNote:'Tạo biên bản từ nội dung chat hiện tại.',minutesCreate:'Tạo biên bản',minutesWorking:'Đang tạo biên bản…',minutesClose:'Đóng',saveTxt:'Lưu TXT',savePdf:'Lưu PDF',summary:'Tóm tắt',decisions:'Quyết định',actions:'Hạng mục thực hiện',unresolved:'Vấn đề chưa giải quyết',none:'Không có',minutesFail:'Không thể tạo biên bản cuộc họp.'},
zh:{tagline:'5种语言实时会议翻译',loginTitle:'登录',loginDesc:'选择语言，输入用户ID和姓名，然后开始。',idLabel:'用户ID / 员工编号',nameLabel:'姓名',start:'开始',loginNote:'所选语言会同时应用于整个界面和收到的消息翻译。',connected:'已连接',createTitle:'创建会议室',createDesc:'以主持人身份创建会议室，参与者需批准后才能聊天。',roomName:'会议室名称',create:'创建会议室',joinTitle:'加入会议室',joinDesc:'输入6位房间代码并等待主持人批准。',code:'房间代码',join:'发送参加请求',roomInfo:'会议室',room:'会议室',role:'角色',language:'语言',count:'参与者',participants:'参与者管理',refresh:'刷新',security:'只有已批准的房间成员才能读取、发送和翻译消息。',chat:'会议聊天',waitingTitle:'等待主持人批准',waitingDesc:'主持人批准后此页面会自动更新。',blockedTitle:'无法进入',blockedDesc:'主持人已拒绝或移除此参与者。',send:'发送',logout:'退出',host:'主持人',member:'参与者',approve:'批准',reject:'拒绝',remove:'移除',pending:'等待批准',approved:'已批准',noPending:'没有待批准参与者。',type:'输入消息…',working:'正在连接…',creating:'正在创建会议室…',joining:'正在发送请求…',translate:'正在翻译…',invalidId:'用户ID请使用2–40个字母、数字、点、下划线或连字符。',needName:'请输入姓名。',duplicate:'该用户ID已被使用。',loginFail:'登录失败。',needRoom:'请输入会议室名称。',createFail:'创建会议室失败。',badCode:'请输入有效的6位房间代码。',joinFail:'参加请求失败。',roomFull:'会议室已满。',notFound:'找不到会议室或会议室已关闭。',decisionFail:'无法更新参与者。',original:'原文',minutesTitle:'会议纪要',minutesNote:'根据当前聊天内容生成会议纪要。',minutesCreate:'生成会议纪要',minutesWorking:'正在生成会议纪要…',minutesClose:'关闭',saveTxt:'保存TXT',savePdf:'保存PDF',summary:'会议摘要',decisions:'决定事项',actions:'行动项目',unresolved:'未解决事项',none:'无',minutesFail:'无法生成会议纪要。'},
ja:{tagline:'5言語リアルタイム会議翻訳',loginTitle:'ログイン',loginDesc:'言語を選択し、ユーザーIDと名前を入力して開始してください。',idLabel:'ユーザーID / 社員番号',nameLabel:'名前',start:'開始',loginNote:'選択した言語が画面全体と受信メッセージの翻訳言語に適用されます。',connected:'接続済み',createTitle:'会議室を作成',createDesc:'ホストとして会議室を作成します。参加者は承認後にチャットできます。',roomName:'会議室名',create:'会議室作成',joinTitle:'会議室に参加',joinDesc:'6桁のルームコードを入力し、ホストの承認を待ちます。',code:'ルームコード',join:'参加リクエスト',roomInfo:'会議室',room:'会議室',role:'役割',language:'言語',count:'参加者',participants:'参加者管理',refresh:'更新',security:'承認された参加者だけがメッセージの閲覧・送信・翻訳を行えます。',chat:'会議チャット',waitingTitle:'ホスト承認待ち',waitingDesc:'ホストが承認するとこの画面は自動で更新されます。',blockedTitle:'入室不可',blockedDesc:'ホストが参加申請を拒否または参加者を退出させました。',send:'送信',logout:'ログアウト',host:'ホスト',member:'参加者',approve:'承認',reject:'拒否',remove:'退出',pending:'承認待ち',approved:'承認済み',noPending:'承認待ち参加者はいません。',type:'メッセージを入力…',working:'接続中…',creating:'会議室作成中…',joining:'参加リクエスト送信中…',translate:'翻訳中…',invalidId:'ユーザーIDは英数字・ピリオド・アンダースコア・ハイフンで2～40文字入力してください。',needName:'名前を入力してください。',duplicate:'このユーザーIDは既に使用されています。',loginFail:'ログインに失敗しました。',needRoom:'会議室名を入力してください。',createFail:'会議室作成に失敗しました。',badCode:'有効な6桁のルームコードを入力してください。',joinFail:'参加リクエストに失敗しました。',roomFull:'会議室は満員です。',notFound:'会議室が見つからないか終了しています。',decisionFail:'参加者の状態を更新できませんでした。',original:'原文',minutesTitle:'議事録',minutesNote:'現在のチャット内容から議事録を作成します。',minutesCreate:'議事録作成',minutesWorking:'議事録作成中…',minutesClose:'閉じる',saveTxt:'TXT保存',savePdf:'PDF保存',summary:'会議要約',decisions:'決定事項',actions:'実行項目',unresolved:'未解決項目',none:'なし',minutesFail:'議事録を作成できませんでした。'}
};

const $=id=>document.getElementById(id);
let lang='en',session=null,profile=null,state=null,lastId=0,rendered=new Set(),loadingMessages=false,msgTimer=null,memberTimer=null,statusTimer=null;

function t(k){return I18N[lang]?.[k]||I18N.en[k]||k}
function setStatus(id,msg,ok=false){$(id).textContent=msg;$(id).className='status '+(msg?(ok?'ok':'err'):'')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function headers(token,json=true){const h={apikey:KEY};if(json)h['content-type']='application/json';if(token)h.authorization='Bearer '+token;return h}
function saveSession(){localStorage.setItem(KSESSION,JSON.stringify(session))}
function saveState(){localStorage.setItem(KSTATE,JSON.stringify(state))}
function clearLocal(){localStorage.removeItem(KSESSION);localStorage.removeItem(KSTATE)}
function loadJSON(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function langName(code){return {en:'English',ko:'한국어',vi:'Tiếng Việt',zh:'简体中文',ja:'日本語'}[code]||code}
function code6(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';crypto.getRandomValues(new Uint32Array(6)).forEach(n=>s+=chars[n%chars.length]);return s}

function applyLang(v){
 lang=I18N[v]?v:'en';document.documentElement.lang=lang;$('uiLang').value=lang;
 const M={tagline:'tagline',loginTitle:'loginTitle',loginDesc:'loginDesc',idLabel:'idLabel',nameLabel:'nameLabel',startBtn:'start',loginNote:'loginNote',welcomeTitle:'connected',createTitle:'createTitle',createDesc:'createDesc',roomNameLabel:'roomName',createBtn:'create',joinTitle:'joinTitle',joinDesc:'joinDesc',codeLabel:'code',joinBtn:'join',roomInfoTitle:'roomInfo',roomLabel:'room',roleLabel:'role',languageLabel:'language',countLabel:'count',participantsTitle:'participants',refreshMembersBtn:'refresh',securityNote:'security',chatTitle:'chat',connectionText:'connected',waitingTitle:'waitingTitle',waitingDesc:'waitingDesc',blockedTitle:'blockedTitle',blockedDesc:'blockedDesc',sendBtn:'send',logoutBtn:'logout',minutesTitle:'minutesTitle',minutesNote:'minutesNote',minutesBtn:'minutesCreate',minutesModalTitle:'minutesTitle',minutesCloseBtn:'minutesClose',saveTxtBtn:'saveTxt',savePdfBtn:'savePdf'};
 for(const [id,key] of Object.entries(M))if($(id))$(id).textContent=t(key);
 $('messageInput').placeholder=t('type');
 if(profile){$('languageOut').textContent=langName(profile.language)}
 if(state?.mode){$('roleOut').textContent=state.mode==='host'?t('host'):t('member')}
}

async function refreshAuth(){
 if(!session?.refresh_token)return null;
 const r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:headers(),body:JSON.stringify({refresh_token:session.refresh_token})});
 if(!r.ok)return null;const j=await r.json();
 session={...session,access_token:j.access_token,refresh_token:j.refresh_token||session.refresh_token,user_id:j.user?.id||session.user_id};saveSession();return session;
}
async function authFetch(url,opt={}){
 const method=(opt.method||'GET').toUpperCase();
 opt.headers={...(opt.headers||{}),...headers(session?.access_token,method!=='GET')};
 let r=await fetch(url,opt);
 if(r.status===401&&session){const n=await refreshAuth();if(n){opt.headers={...(opt.headers||{}),...headers(n.access_token,method!=='GET')};r=await fetch(url,opt)}}
 return r;
}
async function readProfile(){
 const r=await authFetch(SB+'/rest/v1/profiles?user_id=eq.'+encodeURIComponent(session.user_id)+'&select=user_id,login_id,display_name,language',{method:'GET'});
 if(!r.ok)return null;const rows=await r.json();return rows?.[0]||null;
}
